# Generated by Django 5.0 on 2024-01-26 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='quantity',
            new_name='cart_quantity',
        ),
    ]
